language: ruby
rvm:
- 2.3
before_script:
- bundle exec rake db:setup
script:
- bundle exec rspec spec
notifications:
  slack:
    secure: XY15YsaBiZbWt/YPZ4jP4vOgZU+P7DfsozGAYyxHjumfuUwZXBI2sW5EMtILVImSXPhKzoKzV5GOm72Pye6ei0YTBlTZeZ1i1MH+jC3wK2wXInrRqQLhYy+bnSdt5J6GLt3jF0WBoNpabU9U5Zmgvbq9LF8QbbjmFE5YQmJyHao=
deploy:
  provider: script
  script: "./travis-build.sh"
  on:
    all_branches: true
