version: '2.0'

services:
  db:
    image: mysql:5.6
    platform: linux/amd64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    working_dir: /app
    environment:
      RAILS_ENV:
      DATABASE_HOST: 'db'
    tmpfs: /app/tmp
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
    command: 'rails server'
    ports:
      - 3000

  jobs_work:
    <<: *rails
    command: 'rake jobs:work'
    ports: []

  hub_import:
    <<: *rails
    command: 'rake hub:import'
    ports: []

volumes:
  db:
  bundle:
