version: '2.0'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  web: &rails
    build: .
    environment:
      DATABASE_URL: 'mysql2://root@db/pollit'
    tmpfs: /app/tmp
    depends_on:
      - db

  jobs_work:
    <<: *rails
    command: 'rake jobs:work'
    ports: []

  hub_import:
    <<: *rails
    command: 'rake hub:import'
    ports: []

volumes:
  db:
