development:
  url: http://nuntium.instedd.org
  account: bcardiff
  password: pollit
  application: pollit-dev
  at_post_user: pollit
  at_post_pass: pollit
test:
  url: http://nuntium.instedd.org
  account:
  password:
  application:
  at_post_user: test_user
  at_post_pass: test_pass
production:
  url: http://nuntium.instedd.org
  account:
  password:
  application:
  at_post_user:
  at_post_pass:
