development:
  url: http://nuntium.manas.com.ar
  account: pollit
  application: pollit-mhick
  password: pollit
test:
  url: 
  account: 
  application: 
  password: 
production:
  url: 
  account: 
  application: 
  password: 