# Strings manually set to translate
_('Password')
_('Password confirmation')
_('Remember me')

# Generate this content by running rake gettext:store_model_attributes and copy it from config/locales here
_('answer')
_('Answer|Response')
_('channel')
_('Channel|Name')
_('Channel|Address')
_('poll')
_('Poll|Title')
_('Poll|Description')
_('Poll|Form url')
_('Poll|Welcome message')
_('Poll|Status')
_('Poll|Post url')
_('Poll|Confirmation word')
_('Poll|Goodbye message')
_('question')
_('Question|Title')
_('Question|Description')
_('Question|Kind')
_('Question|Options')
_('Question|Numeric max')
_('Question|Numeric min')
_('Question|Field name')
_('Question|Position')
_('respondent')
_('Respondent|Phone')
_('Respondent|Pushed at')
_('Respondent|Pushed status')
_('Respondent|Confirmed')
_('Respondent|Current question sent')
_('user')
_('User|Email')
_('User|Encrypted password')
_('User|Reset password token')
_('User|Reset password sent at')
_('User|Remember created at')
_('User|Sign in count')
_('User|Current sign in at')
_('User|Last sign in at')
_('User|Current sign in ip')
_('User|Last sign in ip')
_('User|Name')
_('User|Google token')
_('User|Confirmation token')
_('User|Confirmed at')
_('User|Confirmation sent at')
_('User|Lang')
